name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Prepare Docker image build metadata
        id: prepare-docker-image-build-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository_owner}}/surfshark
          flavor: latest=false
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64
            linux/ppc64le
            linux/s390x
          push: true
          tags: ${{steps.prepare-docker-image-build-metadata.outputs.tags}}
          labels: ${{steps.prepare-docker-image-build-metadata.outputs.labels}}
